### ISSUE TITLE
Article duplicate filtering and removal (Front-End)

### ISSUE THREAD

**Issue by WinstonHall** [Two-Boys-and-a-Dream/vg-web#43] opened 2023-01-13 22:14 UTC
This is a good find. Our news caching happens every hour, grabbing the 10 most recent gaming articles. During the day, new articles are constantly posted. At night, that is highly unlikely. The most noticeable time to see duplications would be during the evening. Ideally the API should check for uniques before storing articles. I think it also wouldn't hurt for the Front-End to create a unique set (filter out dupes), in case the BE fails.

_Originally posted by @Raymond-Cox in https://github.com/Two-Boys-and-a-Dream/vg-web/issues/36#issuecomment-1381992124_

**Comment by Raymond-Cox** [comment] 2023-01-13 22:23
Duplicate of original #36

**Closed by Raymond-Cox** 2023-01-13 22:23 UTC
